config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  devise_scope :user do
    get 'users/sign_in', to: 'users/sessions#new', as: 'new_user_session'
    get 'users/sign_out', to: 'users/sessions#destroy', as: 'destroy_user_session'
  end

  resources :users, only: %i[create destroy edit update]
  
  namespace :users do
    resources :friends, only: [:index]
    get "friends/search", to: "friends#search"
  end
  
  resources :dashboard, module: :users, only: [:index]
  resources :referral, module: :users, only: [:index]


  resources :utilities, only: [:index], as: 'utilities'

  resources :sessions, only: [:create]
  get 'about', to: 'welcome#about', as: 'about'
  get 'contact', to: 'welcome#contact', as: 'contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  devise :omniauthable, omniauth_providers: [:google_oauth2]

  validates :email, presence: true
  validates_uniqueness_of :email, case_sensitive: false

  def self.from_google(email:, full_name:, uid:, avatar_url:)
    create_with(uid: uid, full_name: full_name, avatar_url: avatar_url).find_or_create_by!(email: email)
  end

  def friends
    friendships = UsersService.get_friends(self.id)[:data]
    friend_ids = friendships.map {|friendship| friendship[:attributes][:following_id]}
    User.where(id: friend_ids)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user
  # before_action :authenticate_user!

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def check_user
    redirect_to new_user_session_path unless current_user
  end
end

app/controllers/users/dashboard_controller.rb
class Users::DashboardController < ApplicationController
  before_action :check_user
  before_action :check_household

  def index
    begin
      @data_info_usage = DashboardFacade.build_usages(params, current_user)
      @usage = DashboardFacade.user_usage(UsersService.call_utility(current_user.id)[:data]
      .first[:attributes])
      @friends = current_user.friends
    rescue
    end
  end

  private

  def check_household
    redirect_to edit_user_path(current_user) unless current_user.household_size
  end
end

app/controllers/users/friends_controller.rb
class Users::FriendsController < ApplicationController
  def search
    friend = User.find_by(email: params[:query])

    if friend
      FriendsFacade.create_friendship(current_user.id, friend.id)
      flash[:succes] = "You are now following #{friend.full_name}!"
      redirect_to dashboard_index_path
    else
      flash[:error] = "User doesn't exist!"
      redirect_to dashboard_index_path
    end
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  skip_before_action :verify_authenticity_token

  def google_oauth2
    user = User.from_google(from_google_params)
    if user.present?
      sign_out_all_scopes
      flash[:success] = t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in(user)
      session[:user_id] = user.id
      if user.household_size
        redirect_to dashboard_index_path
      else
        redirect_to edit_user_path(user)
      end
    else
      flash[:alert] =
        t 'devise.omniauth_callbacks.failure', kind: 'Google', reason: "#{auth.info.email} is not authorized."
      redirect_to new_user_session_path
    end
  end

  protected

  def after_omniauth_failure_path_for(_scope)
    new_user_session_path
  end

  # def after_sign_in_path_for(resource_or_scope)
  #   dashboard_index_path || root_path
  # end

  private

  def from_google_params
    @from_google_params ||= {
      uid: auth.uid,
      email: auth.info.email,
      full_name: auth.info.name,
      avatar_url: auth.info.image
    }
  end

  def auth
    @auth ||= request.env['omniauth.auth']
  end
end

app/controllers/users/referral_controller.rb
class Users::ReferralController < ApplicationController
  before_action :check_user
  def index
    begin
      session[:referral] = params[:referral]
      @message = UsersService.get_meters(params)
    rescue
      flash[:notice] = "Something went wrong"
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def edit; end

  def update
    current_user.update(user_params)
    redirect_to dashboard_index_path
  end
  
  private

  def user_params
    params.require(:user).permit(:household_size, :total_points)
  end
end

app/controllers/utilities_controller.rb
class UtilitiesController < ApplicationController
  def index
    email = current_user.email
    utility = params[:utility]
    data = UsersService.new_user_utility(email, utility)
    redirect_to data
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    redirect_to dashboard_index_path if current_user
  end

  def contact; end

  def about; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def provider_list
    UsersService.fetch_utilities[:data]
    # rescue [{"attributes" => {"name" => "Utilities not found", "id" => "nil"}}]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RunTheJoules</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield :charts_js %>
    <style>
      .flash__alert   { color: red; }
      .flash__notice  { color: blue; }
      .flash__success { color: green; }
    </style>
  </head>

  <body class="flex flex-col min-h-screen">
    <section id="flash-messages" >
      <% flash.each do |notice, messages| %>
        <% if messages.class == Array %>
          <p><%= messages.to_sentence %></p>
        <% else %>
          <p><%= messages%></p>
        <% end %>
      <% end %>
    </section>

    <main class="site-main px-6 flex-grow my-4">
      <% if current_user %>
        <%= render partial: "shared/logged_in_menu" %>
      <% else %>
        <%= render partial: "shared/logged_out_menu" %>
      <% end %>
      <%= yield %>
    </main>

    <footer class="mb-3 -mt-2 w-full items-center">
      <ul class="text-center list-none space-x-6">
        <li class="inline-block gap-6">
          <%=  link_to 'Contact Us', contact_path %>
        </li>
        <li class="inline-block gap-6">
          <%= link_to 'About Us', about_path %>
        </li>
        <li class="inline-block gap-6">
          <a href="https://utilityapi.com">Utility Api</a>
        </li>
      </ul>
    </footer>
    <%= javascript_include_tag 'custom', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/shared/_logged_in_menu.html.erb
<div class="flex flex-col-h-screen">
  <section class="mb-24 -mt-2">
    <ul class="grid grid-flow-col col-start-1 col-end-auto grid-cols-max-content gap-3 list-none md:flex md:flex-wrap -mx-6 md:mx-0 py-1 md:py-2 overflow-x-auto md:overflow-x-visible scrolling-touch scrollbar-hidden " >
    
      <li class="flex-none inline-flex">
        <%= link_to "Dashboard", root_path, class: "button rounded-lg py-1 md:py-2 px-5 bg-blue-400 hover:bg-blue-500 hover:text-white focus:bg-blue-500 focus:text-white transition duration-150-ease-in-out" %>
      </li>
      
      <li class="flex-none inline-flex">
        <%= link_to "Log Out", destroy_user_session_path, class: "button rounded-lg py-1 md:py-2 px-5 bg-blue-600 hover:bg-blue-500 hover:text-white focus:bg-blue-500 focus:text-white transition duration-150-ease-in-out" %><br>
      </li>
      <%= render "users/dashboard/navbar" %>
    </ul>
  </section>
</div>

app/views/shared/_logged_out_menu.html.erb
<div class="flex flex-col-h-screen text-white">
  <section class="mb-24 -mt-2">
    <ul class="grid grid-flow-col col-start-1 col-end-auto grid-cols-max-content gap-3 list-none md:flex md:flex-wrap -mx-6 md:mx-0 py-1 md:py-2 overflow-x-auto md:overflow-x-visible scrolling-touch scrollbar-hidden " >
      <li class="flex-none inline-flex">
        <%= link_to "Home", root_path, class: "button rounded-lg py-1 md:py-2 px-5 bg-blue-400 hover:bg-blue-500 hover:text-white focus:bg-blue-500 focus:text-white transition duration-150-ease-in-out" %>
      </li>
      <li class="flex-none inline-flex">
        <%= link_to "Log In", user_google_oauth2_omniauth_authorize_path, method: :post, class: "button rounded-lg py-1 md:py-2 px-5 bg-blue-400 hover:bg-blue-500 hover:text-white focus:bg-blue-500 focus:text-white transition duration-150-ease-in-out" %><br>
      </li>
      <li class="flex-none inline-flex">
        <%= link_to "Sign Up", user_google_oauth2_omniauth_authorize_path, method: :post, class: "button rounded-lg py-1 md:py-2 px-5 bg-blue-400 hover:bg-blue-500 hover:text-white focus:bg-blue-500 focus:text-white transition duration-150-ease-in-out" %><br>
      </li>
    </ul>
  </section>
</div>

app/views/users/dashboard/_friends_search.html.erb
<%= form_with url: users_friends_search_path, method: :get, local: true do |f| %>
    <%= f.text_field :query, value: "email", :style => "border: solid; border-style: solid; border-color: rgba(209, 213, 219);" %>
    <%= f.submit "Follow Friend", class: "button rounded-lg bg-gray-300 px-8 " %>
<% end %>

app/views/users/dashboard/_monthly.html.erb
<h1> <%= month.monthly_points %></h1>
<%= month.end_date %>'s usage: <%= month.kwh %> kwh</h2>

app/views/users/dashboard/_navbar.html.erb
<li class="flex-none inline-flex">
  <button id="friends-btn" class="button rounded-lg py-1 md:py-2 px-5 bg-blue-200 hover:bg-blue-500 hover:text-white focus:bg-blue-500 focus:text-white transition duration-150-ease-in-out">Friends List</button>
</li>
<%= render "users/dashboard/friends/panel" %>

app/views/users/dashboard/friends/_friend.html.erb
<%= friend.email%><br>

app/views/users/dashboard/friends/_panel.html.erb
<div class="modal friend-modal">
  <div class="modal-content">
    <span class="close-btn close-friends-btn">&times;</span>
    <header class="flex flex-col items-center">
      <%= "Your Friends List" %>
    </header>
    <% if current_user.friends %>
      <%= render(partial: "users/dashboard/friends/friend", collection: current_user.friends) || "You currently have no friends." %>
    <% end %>
  </div>
</div>

app/views/users/dashboard/index.html.erb
<h1>Welcome, <%= current_user.full_name %></h1>

<% if not session[:referral] || @usage %>
  <%= form_with url: utilities_path, method: :get, local: true do |f| %>
    <%= f.select :utility, provider_list.map {|utility| [utility[:attributes][:name], utility[:attributes][:id]]}, :style => "border: solid; border-style: solid; border-color: gray;", prompt: "select-field"  %>
    <%= f.submit 'Authorize Provider', class: "button rounded-lg bg-gray-300 px-8 " %>
  <% end %>
<% end %>

<section id="add-friend-section" class="border-solid border-gray-700">
  <%= render partial: "friends_search"%>
</section><br><br>

<div class="panels container bg-gray-200 w-full mx-auto type-page rounded-lg">
  <div class="grid grid-cols-2 gap-12 md:gap-12 md:grid-cols-auto rounded-lg scrolling-touch scrollbar-hidden overflow-x-scroll md:overflow-auto mx-6 md:mx-0">
  <section class="my-usages bg-gray-200">
  <header class="flex flex-col items-center bg-gray-200 font-bold rounded-lg text-2xl">
  <p> My Monthly Points </p>
  </header>
    <% if @data_info_usage %>
        <div class="grid gap-12 md:gap-12 rounded-lg scrolling-touch scrollbar-hidden overflow-x-scroll md:overflow-auto mx-6 md:mx-0">
        <% friend_count = @data_info_usage[:friends].count %>
        <% friend_count.times do %>
          <%= column_chart [[@usage.user.full_name, @usage.monthly_points]] %>
          <section id="points-breakdown-section">
            <p><b><%= @data_info_usage[:user_usage].name %></b>: <%= @usage.monthly_points %> points this month</p>
          </section>
        <% end %>
        </div>
    <% else %>
        <p>Authorize your provider above to see your monthly points</p>
    <% end %>
      </section>

      <section id="friends-section" class="parties_im_invited_to bg-gray-200">
        <header class="flex flex-col items-center bg-gray-200 font-bold rounded-lg text-2xl">
          <h3> My Friends Monthly Points </h3>
        </header>
    <% if @data_info_usage %>
        <div class="grid  gap-12 md:gap-12 rounded-lg scrolling-touch scrollbar-hidden overflow-x-scroll md:overflow-auto mx-6 md:mx-0">
        <% @data_info_usage[:friends].each do |friend| %>
          <%= column_chart [[friend.user.full_name, friend.monthly_points]] %>
          <section id="friend-points-breakdown-section">
            <p><b><%= friend.user.full_name %></b>: <%= friend.monthly_points %> points this month</p>
          </section>
        <% end %>
        </div>
    <% end %>
      </section>
  </div>        
</div>

app/views/users/edit.html.erb
<%= form_with model: current_user, method: :patch, local: true do |f| %>
  <%= f.label "Household size:" %>
  <%= f.text_field :household_size %>
  <%= f.submit %>
<% end %>

app/views/users/friends/_friend_search.html.erb
<%= form_with url: user_friends_search_path, method: :get, local: true do |f| %>
  <%= f.text_field :query %>
  <%= f.submit "Follow Friend" %>
<% end %>

app/views/users/friends/_friends_search.html.erb
<%= form_with url: users_friends_search_path, method: :get, local: true do |f| %>
  <%= f.text_field :query %>
  <%= f.submit "Follow Friend" %>
<% end %>

app/views/users/referral/index.html.erb
<%= current_user.full_name %>
<%= @message[:data] %>

app/views/welcome/about.html.erb
<h1>About Us</h1><br>

<p>At Turing we study software design with an emphasis on the power that good design has to change the world. With this project we wanted to make it easier to track and compare the footprint of our electricity use. Sign in, invite your friends, and see if impact is as small as you hope.</p><br>

<h3> Find out more about what each of us is up to below.</h3><br>
<p> Alex Osborne - <a href="https://github.com/AlexanderOsborne">Github</a> - <a href="https://www.linkedin.com/in/alex-osborne/">LinkedIn</a></p><br>
<p> Aiden Mendez - <a href="https://github.com/aidenmendez">Github</a> - <a href="https://www.linkedin.com/in/aiden-mendez/)">LinkedIn</a></p><br>
<p> Catherine Dean - <a href="https://github.com/catherinemdean15">Github</a> - <a href="https://www.linkedin.com/in/catherine-dean-57a92030/">LinkedIn</a></p><br>
<p> James Fox-Collis - <a href="https://github.com/jlfoxcollis">Github</a> - <a href="https://www.linkedin.com/in/james-fox-collis/">LinkedIn</a></p><br>
<p> Robert Heath - <a href="https://github.com/kaiheiongaku">Github</a> - <a href="https://www.linkedin.com/in/robert-heath-ii/">LinkedIn</a></p><br>
<p> Joe Jiang - <a href="https://github.com/ninesky00">Github</a> - <a href="https://www.linkedin.com/in/joe-jiang-0a655882/">LinkedIn</a></p><br>

app/views/welcome/contact.html.erb
<h1>Contact Us</h1><br>

<p>Interested in scaling this up? Want to get your utility or local goverment involved? So do we! Reach out to any of us via the links below.</p><br>


<p> Alex Osborne - <a href="https://github.com/AlexanderOsborne">Github</a> - <a href="https://www.linkedin.com/in/alex-osborne/">LinkedIn</a></p><br>
<p> Aiden Mendez - <a href="https://github.com/aidenmendez">Github</a> - <a href="https://www.linkedin.com/in/aiden-mendez/)">LinkedIn</a></p><br>
<p> Catherine Dean - <a href="https://github.com/catherinemdean15">Github</a> - <a href="https://www.linkedin.com/in/catherine-dean-57a92030/">LinkedIn</a></p><br>
<p> James Fox-Collis - <a href="https://github.com/jlfoxcollis">Github</a> - <a href="https://www.linkedin.com/in/james-fox-collis/">LinkedIn</a></p><br>
<p> Robert Heath - <a href="https://github.com/kaiheiongaku">Github</a> - <a href="https://www.linkedin.com/in/robert-heath-ii/">LinkedIn</a></p><br>
<p> Joe Jiang - <a href="https://github.com/ninesky00">Github</a> - <a href="https://www.linkedin.com/in/joe-jiang-0a655882/">LinkedIn</a></p><br>

app/views/welcome/index.html.erb
<div class="grid w-full justify-items-center grid-cols-2  divide-gray-500 space-x-6 bg-white">

  <section class='grid grid-gutter items-center p-11 border-gray-900 space-y-6 font-sans Roboto'>
    <h1 class="text-left text-5xl font-bold text-blue-700">Run the Joules</h1>
    <p class="text-xl">Track energy usage, earn points, and compete with neighbors. RTJ automatically syncs monthly usage data across dozens of utility providers.</p>
  </section>

  <section class="relative pl-4 -mr-40 sm:mx-auto sm:max-w-3xl sm:px-0 lg:max-w-none lg:h-full lg:pl-12 h-screen object-cover bg-right shadow-2xl pt-6">
    <%= image_tag("hero-image.png") %>
  </section>
</div>